# Generated by Django 4.1.7 on 2023-11-07 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alergie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Naam", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Klant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("GezinsNaam", models.CharField(max_length=100)),
                ("Volwassenen", models.IntegerField()),
                ("Kinderen", models.IntegerField()),
                ("Babies", models.IntegerField()),
                ("Postcode", models.CharField(max_length=50)),
                ("Varkesvlees", models.BooleanField()),
                ("Vegataries", models.BooleanField()),
                ("Veganistisch", models.BooleanField()),
                (
                    "Alergieën",
                    models.ManyToManyField(related_name="klant", to="Klanten.alergie"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BSN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("BSN", models.IntegerField()),
                ("volledigeNaam", models.CharField(max_length=100)),
                (
                    "Klant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Klanten.klant",
                    ),
                ),
            ],
        ),
    ]
