# Generated by Django 4.1.7 on 2023-11-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Leverancier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("BedrijfsNaam", models.CharField(max_length=100)),
                ("Adres", models.CharField(max_length=100)),
                ("ContactPersoon", models.CharField(max_length=100)),
                ("Telefoon", models.IntegerField()),
                ("Email", models.EmailField(max_length=254)),
                ("LeveringsDatum", models.DateField()),
            ],
        ),
    ]
