# Generated by Django 4.1.7 on 2023-11-07 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Klanten", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Catagorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Naam", models.CharField(max_length=100)),
                ("Omschrijving", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("EAN", models.IntegerField()),
                ("Afbeelding", models.ImageField(upload_to="")),
                ("Varkesvlees", models.BooleanField()),
                ("Vegataries", models.BooleanField()),
                ("Veganistisch", models.BooleanField()),
                (
                    "Catagorieën",
                    models.ManyToManyField(
                        related_name="product", to="magazijn.catagorie"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("HoudsbaarheidDatum", models.DateField()),
                ("Status", models.IntegerField()),
                (
                    "Product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="magazijn.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pakket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("UitgiftDatum", models.DateField()),
                (
                    "GezinsNaam",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Klanten.klant",
                    ),
                ),
            ],
        ),
    ]
