# Generated by Django 4.1.7 on 2023-11-07 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("magazijn", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productitem",
            name="Pakket",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="magazijn.pakket",
            ),
        ),
    ]
