# Generated by Django 4.1.7 on 2023-11-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magazijn", "0002_productitem_pakket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="Afbeelding",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
