# Generated by Django 4.1.7 on 2023-11-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazijn', '0002_productitem_pakket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagorie',
            name='Naam',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
