# Generated by Django 4.1.7 on 2023-11-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magazijn", "0003_alter_product_afbeelding"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="voorraad",
            field=models.IntegerField(default=0),
        ),
    ]
