# Generated by Django 4.1.7 on 2023-11-16 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("directie", "0001_initial"),
        ("magazijn", "0004_product_voorraad"),
    ]

    operations = [
        migrations.AddField(
            model_name="productitem",
            name="leverancier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="directie.leverancier",
            ),
        ),
    ]
